server:
  port: 8080
#spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
datasource:
  username : ${DATABASE_USERNAME}
  password : ${DATABASE_PASSWORD}
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/chapter_96
datasource2:
  username : ${DATABASE_USERNAME}
  password : ${DATABASE_PASSWORD}
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/chapter_97

jwt:
  secret-key-source:${JWT_SECRET_KEY}