spring:
  config:
    activate:
      on-profile: local
server:
  port: 8080
logging:
  config: classpath:logback-spring-local.xml
  level:
    org:
      hibernate:
        SQL: DEBUG

#  리소스 하위 경로가 classpath
